export interface FeatureDefinition {
  id: string;
  name: string;
  route: string;
  icon?: string;
  sidebarVisibility: boolean;
  requiredRoles: string[];
  pageTitle: string;
  category: string;
  order: number;
}

export const FEATURE_REGISTRY: FeatureDefinition[] = [
  {
    id: 'dashboard',
    name: 'Dashboard',
    route: '/',
    sidebarVisibility: true,
    requiredRoles: ['Super Admin', 'City Manager', 'Support Agent', 'Field Staff', 'Finance'],
    pageTitle: 'Overview',
    category: 'Core',
    order: 10,
  },
  {
    id: 'leads',
    name: 'Leads',
    route: '/leads',
    sidebarVisibility: true,
    requiredRoles: ['Super Admin', 'City Manager', 'Support Agent'],
    pageTitle: 'Lead Management',
    category: 'Sales',
    order: 20,
  },
  {
    id: 'users',
    name: 'Users (Staff)',
    route: '/users',
    sidebarVisibility: true,
    requiredRoles: ['Super Admin', 'City Manager'],
    pageTitle: 'Staff Management',
    category: 'Administration',
    order: 100,
  },
  {
    id: 'cities',
    name: 'Cities',
    route: '/cities',
    sidebarVisibility: true,
    requiredRoles: ['Super Admin'],
    pageTitle: 'City Operations',
    category: 'Administration',
    order: 110,
  },
  {
    id: 'roles',
    name: 'Roles',
    route: '/roles',
    sidebarVisibility: true,
    requiredRoles: ['Super Admin'],
    pageTitle: 'Role Configuration',
    category: 'Administration',
    order: 120,
  },
  {
    id: 'services',
    name: 'Services',
    route: '/services',
    sidebarVisibility: true,
    requiredRoles: ['Super Admin'],
    pageTitle: 'Service Catalogue',
    category: 'Master Data',
    order: 200,
  },
  {
    id: 'pricing-rules',
    name: 'Pricing Rules',
    route: '/pricing-rules',
    sidebarVisibility: true,
    requiredRoles: ['Super Admin'],
    pageTitle: 'Pricing Configuration',
    category: 'Master Data',
    order: 210,
  },
  {
    id: 'customers',
    name: 'Customers',
    route: '/customers',
    sidebarVisibility: true,
    requiredRoles: ['Super Admin', 'City Manager', 'Support Agent', 'Field Staff'],
    pageTitle: 'Customer Management',
    category: 'Sales',
    order: 30,
  },
  {
    id: 'bookings',
    name: 'Bookings',
    route: '/bookings',
    sidebarVisibility: true,
    requiredRoles: ['Super Admin', 'City Manager', 'Support Agent', 'Field Staff'],
    pageTitle: 'Bookings',
    category: 'Operations',
    order: 40,
  },
  {
    id: 'jobs',
    name: 'Jobs',
    route: '/jobs',
    sidebarVisibility: true,
    requiredRoles: ['Super Admin', 'City Manager', 'Support Agent', 'Field Staff'],
    pageTitle: 'Jobs',
    category: 'Operations',
    order: 50,
  },
  {
    id: 'calendar',
    name: 'Calendar',
    route: '/calendar',
    sidebarVisibility: true,
    requiredRoles: ['Super Admin', 'City Manager', 'Support Agent'],
    pageTitle: 'Calendar',
    category: 'Operations',
    order: 60,
  },
  {
    id: 'invoices',
    name: 'Invoices',
    route: '/invoices',
    sidebarVisibility: true,
    requiredRoles: ['Super Admin', 'City Manager', 'Finance'],
    pageTitle: 'Invoices',
    category: 'Finance',
    order: 70,
  },
  {
    id: 'payments',
    name: 'Payments',
    route: '/payments',
    sidebarVisibility: true,
    requiredRoles: ['Super Admin', 'City Manager', 'Finance'],
    pageTitle: 'Payments',
    category: 'Finance',
    order: 80,
  },
  {
    id: 'reports',
    name: 'Reports',
    route: '/reports',
    sidebarVisibility: true,
    requiredRoles: ['Super Admin', 'City Manager', 'Finance'],
    pageTitle: 'Reports',
    category: 'Finance',
    order: 90,
  },
  {
    id: 'expenses',
    name: 'Expenses',
    route: '/expenses',
    sidebarVisibility: true,
    requiredRoles: ['Super Admin', 'City Manager', 'Finance'],
    pageTitle: 'Expense Management',
    category: 'Finance',
    order: 85,
  },
  {
    id: 'quotations',
    name: 'Quotations',
    route: '/quotations',
    sidebarVisibility: true,
    requiredRoles: ['Super Admin', 'City Manager', 'Support Agent', 'Finance'],
    pageTitle: 'Quotations',
    category: 'Finance',
    order: 65,
  },
  {
    id: 'settings',
    name: 'System Settings',
    route: '/settings',
    sidebarVisibility: true,
    requiredRoles: ['Super Admin'],
    pageTitle: 'System Settings',
    category: 'Settings',
    order: 300,
  },
  {
    id: 'complaints',
    name: 'Complaints',
    route: '/complaints',
    sidebarVisibility: true,
    requiredRoles: ['Super Admin', 'City Manager', 'Support Agent', 'Technician'],
    pageTitle: 'Complaint Management',
    category: 'Support',
    order: 65,
  },
  {
    id: 'feedback',
    name: 'Feedback',
    route: '/feedback',
    sidebarVisibility: true,
    requiredRoles: ['Super Admin', 'City Manager', 'Support Agent', 'Field Staff', 'Technician', 'Finance'],
    pageTitle: 'Customer Feedback',
    category: 'Support',
    order: 66,
  },
  {
    id: 'whatsapp',
    name: 'WhatsApp Inbox',
    route: '/whatsapp',
    sidebarVisibility: true,
    requiredRoles: ['Super Admin', 'City Manager', 'Support Agent'],
    pageTitle: 'WhatsApp Inbox',
    category: 'Support',
    order: 67,
  },
];
